Worked on endpoint improvised functionality and fixed bugs
deriv-com/binary-bot pull request #135
Opened 2022-04-01 09:50 UTC by sandeep-deriv

2022-04-05 09:53 UTC, sara-fs commented on src/botPage/view/deriv/layout/Header/components/account-dropdown.jsx
> +import { useLocation } from "react-router-dom";
Can we combine this line with the upper one? `react-router-dom` is being used 2 times.

2022-04-05 09:53 UTC, sara-fs commented on src/botPage/view/deriv/layout/Header/Header.jsx
> +    const landing_company = active_token?.loginInfo.landing_company_name;
After login there is a console error `Uncaught TypeError: Cannot read properties of null (reading 'isSignedIn')
` on your test link, Could you plz check if it is related to your changes? thanks

2022-04-05 09:53 UTC, sara-fs commented on src/botPage/view/deriv/layout/Header/components/account-dropdown.jsx
> +  const logout = () => {
the same console error after logout

2022-04-05 09:53 UTC, sara-fs commented on src/botPage/view/deriv/layout/Header/components/platform-dropdown.jsx
> +        console.log('is it coming here')
can we remove this?

2022-04-05 09:53 UTC, sara-fs commented on src/botPage/view/deriv/components/tour/tour.jsx
> -    const[run, setRun] = useState(() => getTourState());
Tour is not being showed anymore.

2022-04-05 18:44 UTC, mehrzad-fs requested changes

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/layout/Header/Header.jsx
> +    const landing_company = active_token?.loginInfo.landing_company_name;
`isSignedIn` error comes from the Google Drive API. it's not related to these changes.

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/layout/Header/Header.jsx
> +const Header = React.memo(() => {
Do we need `memo` here?

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
>  	}
Is it possible to have one `logout` method for both `endpoint` and `logout` components?

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
> +			if (api && api.disconnect) {
```suggestion
			if (api?.disconnect) {
```

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
>  			$('#error')
Could you please remove jquery from this component?

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
> +			});
```suggestion
			const api = new DerivAPIBasic({
				connection: new WebSocket(socket_url),
			});
```

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/components/tour/tour.jsx
> -    const[run, setRun] = useState(() => getTourState());
If we call tour inside the `Main` component we don't need to update this component 
Currently, we call it on `auth-button` and `account-action` components

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/api.js
> +  connection: deriv_socket,
```suggestion
  connection: new WebSocket(socket_url),
```

2022-04-05 18:44 UTC, mehrzad-fs commented on src/botPage/view/deriv/api.js
> +const deriv_socket = new WebSocket(socket_url);
```suggestion
```

2022-04-05 18:44 UTC, mehrzad-fs commented on gulp/webpack.js
> +    console.log('Project Name: ', name);
```suggestion
```

2022-04-05 18:44 UTC, mehrzad-fs commented on gulp/webpack.js
> +function getProjectName() {
please check if we have git config

2022-04-05 18:44 UTC, mehrzad-fs commented on gulp/webpack.js
> +    const name = path.basename(url, path.extname(url));
by using `exec` and the following command you can get the project name 
basename -s .git `git config --get remote.origin.url`

2022-04-06 02:21 UTC, sandeep-deriv commented on gulp/webpack.js
> +function getProjectName() {
Done

2022-04-06 02:30 UTC, sandeep-deriv commented on gulp/webpack.js
> +    console.log('Project Name: ', name);
I added this intentionally to show the project name while we deploy test link.
just to cross check.

2022-04-06 02:40 UTC, sandeep-deriv commented on src/botPage/view/deriv/api.js
> +  connection: deriv_socket,
actually, the connection accepts Websocket instances only.
I tried providing the socket_url directly but got errors.

2022-04-06 02:41 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/tour/tour.jsx
> -    const[run, setRun] = useState(() => getTourState());
Need more clarification on this.

2022-04-06 02:41 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
> +			if (api && api.disconnect) {
Done

2022-04-06 02:43 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
> +			});
done

2022-04-06 02:48 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Header/Header.jsx
> +    const landing_company = active_token?.loginInfo.landing_company_name;
redeployed with .env it must have been fixed, please try again.

2022-04-06 02:52 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Header/components/account-dropdown.jsx
> +import { useLocation } from "react-router-dom";
I think only useLocation is being imported from `react-router-dom`.
repositioned on top.

2022-04-06 02:54 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Header/components/account-dropdown.jsx
> +  const logout = () => {
Need more clarity 🙏

2022-04-06 02:55 UTC, sandeep-deriv commented on webpack.config.web.js
> +
Done

2022-04-06 02:56 UTC, sandeep-deriv commented on src/botPage/view/deriv/api.js
> +const deriv_socket = new WebSocket(socket_url);
done

2022-04-06 03:00 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Header/Header.jsx
> +const Header = React.memo(() => {
I think its not required, so I removed it.

2022-04-06 03:03 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Header/Header.jsx
> +    console.log('header updateShowMessagePage');
Its already been removed

2022-04-06 03:05 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Header/components/platform-dropdown.jsx
> +        console.log('is it coming here')
![image](https://user-images.githubusercontent.com/90243468/161887760-7cd86609-6c38-4f8c-ab1f-ee29a8b627fe.png)


These consoles have been already removed, not sure how you can see these in changes. 🤔

2022-04-06 09:44 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
>  			$('#error')
Done

2022-04-06 09:48 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
>  	}
We can unite some of the functionality in one method that can be used for both endpoint and logout. But we can not combine it completely, because we have a state event `dispatch(resetClient)` which could only be called from inside a react component. Other than that we can create a common method. But I still suggest keeping these separate for now. 🙏

2022-04-07 09:27 UTC, sandeep-deriv commented on src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
>  	}
done

2022-04-11 05:54 UTC, mehrzad-fs commented on src/botPage/bot/TradeEngine/index.js
> +            }).catch(() => { })
a promise should resolve or reject even catch an error

2022-04-11 06:05 UTC, sandeep-deriv commented on src/botPage/bot/TradeEngine/index.js
> +            }).catch(() => { })
I believe we don't require catch statement here, Removing this.

2022-04-11 12:42 UTC, mehrzad-fs approved these changes

2022-04-11 12:43 UTC, merged