Fix  basket indices chart
deriv-com/binary-bot pull request #164
Opened 2022-05-31 08:46 UTC by sandeep-deriv

added Workaround to fix the basket-indices chart.

2022-06-01 06:47 UTC, mehrzad-fs requested changes

2022-06-01 06:47 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +    const settings = { language: getLanguage() };
```suggestion
```

2022-06-01 06:47 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +            settings={settings}
```suggestion
            settings= { language: getLanguage() }
```

2022-06-01 06:47 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +    const [state, setState] = React.useState({
Please move useStates to the top of the component

2022-06-01 06:47 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +            id="binary-bot-chart"
All props are in alphabetic sort, except `id` could you please move it to the right place?

2022-06-01 06:47 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +    const barriers = [];
Before refactoring we have some cases with the `barriers why do we remove `barriers?

2022-06-01 06:47 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +const ChartContent = ({ api }) => {
is it possible to `import api` instead of getting it as a prop?

2022-06-01 06:55 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
>  const chartHeight = 600;
done

2022-06-01 06:58 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +    const barriers = [];
I have compared it with the DBot app, we are not using any config for barriers,
I have compared the charts before and after removing the barriers config, it doesn't affect anything.

Let me know if we need to keep that config. 🙇

2022-06-01 07:00 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +    const [state, setState] = React.useState({
done

2022-06-01 07:04 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +            settings={settings}
done

2022-06-01 07:05 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +    const settings = { language: getLanguage() };
removed

2022-06-01 07:10 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
>  export default class Chart extends Dialog {
I am not sure If we can do that, because I assume the Dialog is another class, and constructors are being used to overwrite the base class data members.

![image](https://user-images.githubusercontent.com/90243468/171347669-97e300d4-6362-416f-988f-8daa2adfc753.png)


![image](https://user-images.githubusercontent.com/90243468/171347713-7a87562a-5883-48ff-aedb-6ab26b6b1a82.png)

2022-06-02 11:06 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
>  export default class Chart extends Dialog {
> I am not sure If we can do that, because I assume the Dialog is another class, and constructors are being used to overwrite the base class data members.
> 
> ![image](https://user-images.githubusercontent.com/90243468/171347669-97e300d4-6362-416f-988f-8daa2adfc753.png)
> 
> ![image](https://user-images.githubusercontent.com/90243468/171347713-7a87562a-5883-48ff-aedb-6ab26b6b1a82.png)

I think It's possible. you only need to import `Dialog` and instead of extending the class pass the params like this 

```
return(<Dialog
  id="chart-dialog"
  title=...
   content=...
   options=...
>)
```

2022-06-02 11:08 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +    const barriers = [];
> I have compared it with the DBot app, we are not using any config for barriers, I have compared the charts before and after removing the barriers config, it doesn't affect anything.
> 
> Let me know if we need to keep that config. 🙇

In this case you don't need to const `barriers` 
you only need to pass empty object to the chart

2022-06-03 03:30 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +    const barriers = [];
done

2022-06-07 06:33 UTC, maryiafrantsava-binary commented on src/botPage/view/Dialogs/Chart.js
> +    EXPIRYMISS: 'OUTSIDE',
why do we need these updates?

2022-06-07 06:46 UTC, maryiafrantsava-binary commented on src/botPage/view/Dialogs/Chart.js
> -                this.setState({ symbol: s });
why don’t we need to define **symbol** as **s**?

2022-06-07 06:52 UTC, maryiafrantsava-binary commented on src/botPage/view/Dialogs/Chart.js
> +            if (contract.is_sold) {
```suggestion
            if (contract?.is_sold) {
```

2022-06-07 06:53 UTC, maryiafrantsava-binary commented on src/botPage/view/Dialogs/Chart.js
> +                if (contract.high_barrier) {
```suggestion
                if (contract?.barrier) updatedState.high = contract.barrier;
                if (contract?.high_barrier) {
```

2022-06-07 07:05 UTC, maryiafrantsava-binary commented on src/botPage/view/Dialogs/Chart.js
> +        should_barrier_display: false,
why do any variables follow camelСase and any snake_case? I think it will be better to use snake_case here

2022-06-07 07:15 UTC, maryiafrantsava-binary commented on src/botPage/view/Dialogs/Chart.js
> -            ]
why do we need to remove **barriers**? Maybe better to comment it if we decide to use it in the future?

2022-06-07 07:25 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> -            ]
As per my understanding, the barriers are being generated from the server-side, These barriers are not impacting the charts in any way.

Please let me know if we do need these... I have checked on DBot we are not using any sort of barrier config on the front-end. @maryiafrantsava-binary

2022-06-07 07:31 UTC, mehrzad-fs commented on src/botPage/view/Dialogs/Chart.js
> +            if (contract.is_sold) {
> 

We can not do this, because first, we check if we have a contract and then we have different conditions got contract.is_sold and !contract.is_sold

2022-06-07 07:35 UTC, mehrzad-fs approved these changes

2022-06-07 07:38 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> -                this.setState({ symbol: s });
`s` is just a variable name that was being used previously, but now we have `symbol` inside the state,
so making it `symbol` instead of `s` would ease us to update the state and also utilising the ES6 feature same key value.

2022-06-07 07:42 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +            if (contract.is_sold) {
Here we only want to run the inner code if the contract is available...
For this I have made following changes

```javascript
if (!contract) return;
if(contract?.is_sold) {
...
}
```

2022-06-07 07:43 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +                if (contract.high_barrier) {
done

2022-06-07 07:52 UTC, sandeep-deriv commented on src/botPage/view/Dialogs/Chart.js
> +        should_barrier_display: false,
Made all variables follow the same convention `camel_case` 🙇

2022-06-07 08:28 UTC, maryiafrantsava-binary approved these changes

2022-06-22 12:19 UTC, merged