updated readme for binary bot on deriv
deriv-com/binary-bot pull request #165
Opened 2022-06-02 10:09 UTC by farabi-deriv

2022-06-07 07:22 UTC, maryiafrantsava-binary approved these changes

2022-06-07 08:18 UTC, mehrzad-fs requested changes

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
>  In order to run our application for the first time, you need to configure your hosts file:
Could you please add more description of why we need to set up `localbot.binary.com`
e.g: It's impossible to log in on your local machine by using `http://localhost`

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
>  4. Save the file
sometimes you need to reload the `etc/hosts`

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
> + 1. Run ```sudo npm start``` on the binarybot directory. This will open the application in your default browser.
As we run the project on the `port 80` we need to run it with the `sudo` permission

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
> +2.  Navigate to ```http://localbot.binary.sx/bot.html``` (Note that the protocol is ```http``` and not ```https```)
On the binary-bot we have `bot.html` here we have react-router-dom 
```suggestion
2.  Navigate to ```http://localbot.binary.sx``` (Note that the protocol is ```http``` and not ```https```)
```

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
>  1. Make your changes to the source code
you can add `git checkout -b BRANCH_NAME` here

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
> +You can find out about the [Release Process](https://wikijs.deriv.cloud/en/Frontend/binary-bot/release-process) on Wiki.js.
Wiki JS is our internal documents service you should not mention it on the public repo 😱 😱

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
> +2. Manual deployment
We don't need to add `manual deployment` steps

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
>  ENDPOINT='wss://ws.binaryws.com/websockets/v3?l=en&app_id=1169' bot bot-example.js
you can add how to update the endpoint, how to register a new app_id, and what is the endpoint for `localbot.binary.sx`

2022-06-07 08:18 UTC, mehrzad-fs commented on README.md
>  ## Think you found a bug?
Some suggestions:
1- you can add `issues on the setup` by using our internal document
2- also a short description of how to set up the TrackJS and GoogleDrive on the project( it could be short version not as long as we have in our internal docuements)
3- We have the optional branding feature, @sandeep-deriv can help you about

2022-06-07 08:21 UTC, mehrzad-fs commented
@farabi-deriv 
Could you please update your branch to the latest `master` branch updates 
It seems you don't have `Vercel` config so you don't have the test-link

2022-06-07 09:21 UTC, farabi-deriv commented on README.md
> +-   [Manage dependencies](docs/Dependencies/README.md)
Done

2022-06-07 09:21 UTC, farabi-deriv commented on README.md
>  Visual automation for binary bot- [bot.binary.com](https://bot.binary.com)
Done

2022-06-07 09:22 UTC, farabi-deriv commented on README.md
> +1. In order to work with Binary-Bot application, you must create your own version of this project. Please `fork the project` - https://github.com/binary-com/binary-bot to your git account.
Done

2022-06-07 09:24 UTC, farabi-deriv commented on README.md
> + 1. Run ```sudo npm start``` on the binarybot directory. This will open the application in your default browser.
It is already stated to run it with sudo

2022-06-07 09:31 UTC, farabi-deriv commented on README.md
> +2.  Navigate to ```http://localbot.binary.sx/bot.html``` (Note that the protocol is ```http``` and not ```https```)
Done

2022-06-07 09:32 UTC, farabi-deriv commented on README.md
>  1. Make your changes to the source code
Done

2022-06-07 09:32 UTC, farabi-deriv commented on README.md
> +You can find out about the [Release Process](https://wikijs.deriv.cloud/en/Frontend/binary-bot/release-process) on Wiki.js.
Alright. Removing this.

2022-06-07 09:32 UTC, farabi-deriv commented on README.md
> +2. Manual deployment
Ok. Removed

2022-06-07 10:45 UTC, mehrzad-fs commented on README.md
> + - npm >= 6.14.4
Node 14 pass this condition 😄 
node >= 12.18.0

2022-06-08 09:44 UTC, farabi-deriv commented on README.md
>  ENDPOINT='wss://ws.binaryws.com/websockets/v3?l=en&app_id=1169' bot bot-example.js
Alright sure

2022-06-08 09:44 UTC, farabi-deriv commented on README.md
>  ## Think you found a bug?
GoogleDrive setup is already added and now added for optional branding

2022-06-16 03:53 UTC, yashim-deriv approved these changes

2022-06-16 06:01 UTC, mehrzad-fs approved these changes

2022-07-13 08:44 UTC, mehrzad-fs approved these changes

2022-07-13 08:44 UTC, merged