Worked on trackjs issue
deriv-com/binary-bot pull request #203
Opened 2022-08-10 05:30 UTC by sandeep-deriv

Fixed: Added catch statements for api calls and globalobserver error emitter.
Fixed: npm run test Warnings
Fixed: import sequence

2022-08-10 08:23 UTC, maryiafrantsava-binary requested changes

2022-08-10 08:23 UTC, maryiafrantsava-binary commented on src/botPage/view/TradeInfoPanel/TradeTable.js
> +            const contract_info = await _api.send({ proposal_open_contract: 1, contract_id });
```suggestion
            const contract_info = await _api.send({ proposal_open_contract: 1, contract_id }).catch(e => {
                globalObserver.emit('Error', e);
            });
```

2022-08-10 09:12 UTC, maryiafrantsava-binary commented on src/botPage/view/TradeInfoPanel/TradeTable.js
> +            const contract_info = await _api.send({ proposal_open_contract: 1, contract_id });
let me check it in your code and I will be back

2022-08-11 05:15 UTC, sara-fs commented on src/botPage/view/NetworkMonitor.js
> +            }).catch(() => this.parentElement.html('<span class=\'offline\'></span>'));
Isn't it better to show an error message instead of `offline`?

2022-08-12 06:10 UTC, sandeep-deriv commented on src/botPage/view/NetworkMonitor.js
> +            }).catch(() => this.parentElement.html('<span class=\'offline\'></span>'));
Yes, @sara-fs I think its better to show error, changing it. 👍

2022-08-12 07:11 UTC, maryiafrantsava-binary approved these changes
LGTM👍

2022-08-14 03:42 UTC, sara-fs approved these changes

2022-08-24 09:32 UTC, merged