feat: added respected actions for circle-ci config
deriv-com/binary-bot pull request #377
Opened 2023-11-21 05:27 UTC by shayan-deriv

we are migrating from `circle-ci` to `github actions`

2023-11-21 06:54 UTC, shayan-deriv commented on .github/workflows/test.yml
> +    # - uses: actions/checkout@v4.1.0
do we need this?

2023-11-24 06:23 UTC, jim-deriv commented on .github/actions/setup_node/action.yml
> +      node-version: ${{ inputs.node-version}}
@shayan-deriv,  please address the `EOL`

2023-11-24 06:25 UTC, jim-deriv commented on .github/actions/test/action.yml
> +        done
```suggestion
        for i in {1..3}; do
          npm test && break
        done
```
@shayan-deriv, could you please clarify on why the `for` `loop` is necessary? 🤔

2023-11-24 06:26 UTC, shayan-deriv commented on .github/actions/setup_node/action.yml
> +      node-version: ${{ inputs.node-version}}
fixed 🙏

2023-11-24 06:27 UTC, jim-deriv commented on .github/actions/versioning/action.yml
> +
```suggestion
```

2023-11-24 06:32 UTC, shayan-deriv commented on .github/actions/test/action.yml
> +        done
it doesn't make sense for me either. I checked with the binary-bot team . will remove it

2023-11-24 06:35 UTC, jim-deriv commented on .github/workflows/release_staging.yml
> +                  RELEASE_TYPE: staging
```suggestion
```

2023-11-24 06:40 UTC, jim-deriv commented on .github/workflows/test.yml
> +    # - uses: actions/checkout@v4.1.0
@shayan-deriv, Yeah , I agree with you. It doesn't seem necessary to me either

2023-11-24 06:51 UTC, ali-hosseini-deriv requested changes

2023-11-24 06:51 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_cf_pages_production/action.yml
> +    - name: Publish to cloudflare pages (production)
```suggestion
    - name: Publish to cloudflare pages (production)
      env:
          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}       
```
you need to pass the inputs as env to be pickable by wrangler

2023-11-24 06:51 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_cf_pages_staging/action.yml
> +    - name: Publish to cloudflare pages (staging)
ditto

2023-11-24 06:51 UTC, ali-hosseini-deriv commented on .github/workflows/test.yml
> +            - name: Git Cleanup
no need

2023-11-24 06:51 UTC, ali-hosseini-deriv commented on .github/actions/setup_node/action.yml
> +      node-version: ${{ inputs.node-version}}
```suggestion
      node-version: ${{ inputs.node-version }}
```

2023-11-24 06:58 UTC, shayan-deriv commented on .github/actions/publish_to_cf_pages_staging/action.yml
> +    - name: Publish to cloudflare pages (staging)
done

2023-11-24 06:58 UTC, shayan-deriv commented on .github/actions/publish_to_cf_pages_production/action.yml
> +    - name: Publish to cloudflare pages (production)
done

2023-11-24 07:06 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +                  GD_API_KEY: ${{ secrets.GD_API_KEY }}
@vinu-deriv @rupato-deriv do we have different values for these env variables?

2023-11-24 07:26 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +        if: always()
if it's always going to run, do we need this condition here ?

2023-11-24 07:26 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +                  version: ${{ needs.release_production.outputs.RELEASE_VERSION}}
fix EOF

2023-11-24 07:26 UTC, amir-deriv commented on .github/workflows/release_staging.yml
> +                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
fix EOF

2023-11-24 07:26 UTC, amir-deriv commented on .github/actions/setup_node/action.yml
> +      node-version: ${{ inputs.node-version }}
fix EOF

2023-11-24 07:26 UTC, amir-deriv commented on .github/actions/send_slack_notifications/action.yml
> +      shell: bash
fix EOF

2023-11-24 07:26 UTC, amir-deriv commented on .github/actions/publish_to_cf_pages_staging/action.yml
> +      shell: bash
fix EOF

2023-11-24 07:26 UTC, amir-deriv commented on .github/actions/publish_to_cf_pages_production/action.yml
> +      shell: bash
fix EOF

2023-11-24 07:26 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +              uses: './.github/actions/build'
indentation looks inconsistent with the other `.yml` files

2023-11-24 07:34 UTC, shayan-deriv commented on .github/workflows/release_production.yml
> +        if: always()
we still need it. by adding it , the job will run even if the previous job fails. 
https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f

2023-11-24 07:59 UTC, shayan-deriv commented on .github/workflows/release_production.yml
> +              uses: './.github/actions/build'
fixed

2023-11-24 08:04 UTC, jim-deriv approved these changes

2023-11-27 03:55 UTC, rupato-deriv commented
@ali-hosseini-deriv @shayan-deriv can you please check the node_version because last time when we were updating we had set it to 18 and the release was failing on staging so we had downgraded it to 16 because of cjs issue other than this all looks good 👍

2023-11-28 04:36 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +                  GD_API_KEY: ${{ secrets.GD_API_KEY }}
thanks @rupato-deriv 
@shayan-deriv then we have to setup separate `environment` attribute for staging and production workflows. 
please check [this](https://github.com/binary-com/deriv-app/blob/master/.github/workflows/release_production.yml#L9) as reference

2023-11-28 04:54 UTC, shayan-deriv commented on .github/workflows/release_production.yml
> +                  GD_API_KEY: ${{ secrets.GD_API_KEY }}
it's added . thanks guys

2023-12-05 08:55 UTC, merged