sandeep/refactor logtable
deriv-com/binary-bot pull request #49
Opened 2021-11-01 08:29 UTC by sandeep-deriv

2021-11-01 10:21 UTC, mehrzad-fs requested changes

2021-11-01 10:21 UTC, mehrzad-fs commented on src/botPage/view/LogTable.js
> +    }, [rows.length]);
it's better if you use ref for scrolling instead of using jquery

2021-11-01 10:21 UTC, mehrzad-fs commented on src/botPage/view/LogTable.js
> +                return;
```suggestion
         if( !log || !Object.keys(log).length){
               return
          }
     
```

2021-11-01 10:21 UTC, mehrzad-fs commented on src/botPage/view/LogTable.js
> +const min_height = 550;
do we need to define this const outside of our component?

2021-11-01 11:25 UTC, sara-fs commented on src/botPage/view/LogTable.js
> +    }, [rows, id]);
Do we need to have both of rows and id here?

2021-11-01 11:25 UTC, sara-fs commented on src/botPage/view/LogTable.js
> +            globalObserver.unregister('bot.notify', onGetNotification);
Why do we need to have this here?

2021-11-01 11:42 UTC, sandeep-deriv commented on src/botPage/view/LogTable.js
> +const min_height = 550;
I believe there is no need, Let me move this inside the component.

2021-11-01 11:42 UTC, sandeep-deriv commented on src/botPage/view/LogTable.js
> +                return;
Done

2021-11-01 11:56 UTC, sandeep-deriv commented on src/botPage/view/LogTable.js
> +    }, [rows, id]);
Yes, I believe so.
rows and id both are referring to that state when the globalObserver is registered(initially id: 0, rows: []), inside the function onGetNotification the values of rows and id were not getting updated. So in order to sync the state of rows and id inside the onGetNotification function it has to unregister and register with the new state every time the state of rows and id is updated.

2021-11-01 15:54 UTC, sandeep-deriv commented on src/botPage/view/LogTable.js
> +    }, [rows, id]);
It is woking fine with one parameter only `rows` only.

2021-11-02 07:22 UTC, mehrzad-fs commented on src/botPage/view/LogTable.js
> +            globalObserver.unregister('bot.notify', onGetNotification);
it's better to have these observers for now but we will remove them when we refactor all components

2021-11-02 07:24 UTC, mehrzad-fs approved these changes

2021-11-02 08:14 UTC, sara-fs commented on src/botPage/view/LogTable.js
> +            globalObserver.unregister('bot.notify', onGetNotification);
I mean it was componentWillMount and should be replaced with:
```
useEffect(() => {

   }, []); 
```

and no need to add a **return**  inside it because it is as like as **componentWillUnMount** that we didn't have it before.

2021-11-02 12:29 UTC, sandeep-deriv commented on src/botPage/view/LogTable.js
> +            globalObserver.unregister('bot.notify', onGetNotification);
the `return` statement is to clean up the previous subscription with the old state.

2021-11-02 12:31 UTC, sandeep-deriv commented on src/botPage/view/LogTable.js
> +            globalObserver.unregister('bot.notify', onGetNotification);
If I don't do that the state of id and rows inside the function onGetNotification will always keep pointing to 0 and [] (empty array) respectively.

Let me know if we have any other solutions than than this.

2021-11-15 08:13 UTC, mehrzad-fs approved these changes

2021-11-17 08:16 UTC, merged