Added feature to collapse sidebar on mobile devices
deriv-com/binary-bot pull request #75
Opened 2022-01-07 08:27 UTC by sandeep-deriv

2022-01-08 04:38 UTC, salarhfz-fs commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +const SidebarToggler = () => {
```suggestion
const SidebarToggle = () => {
```

2022-01-08 04:40 UTC, salarhfz-fs commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +        const togglerElem = document.getElementById('sidebar-toggle-action');
```suggestion
        const toggleElem = document.getElementById('sidebar-toggle-action');
```

2022-01-08 04:42 UTC, salarhfz-fs commented on src/botPage/view/index.js
> +            const ele = document.getElementById('sidebar-toggle-action');
Which target and which ele? Could we have better naming here?

2022-01-09 07:33 UTC, mehrzad-fs requested changes

2022-01-09 07:33 UTC, mehrzad-fs commented on src/botPage/view/View.js
> +    ReactDOM.render(<SidebarToggler />, document.getElementById('sidebar-toggler'));
Currently, we are rendering our components separately, but we are working on refactoring this structure and having a standard React structure, could you please instead of rendering here move the component in the <Main/> component. then you can remove the #sidebar-toggler from index.mustache

2022-01-09 07:33 UTC, mehrzad-fs commented on src/botPage/view/index.js
> +
please move this part of code inside of the related component, `<SidebarToggle/>`

2022-01-09 07:33 UTC, mehrzad-fs commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +        const togglerElem = document.getElementById('sidebar-toggle-action');
youshould use ref instead of using document.getElementByID('')

2022-01-09 07:33 UTC, mehrzad-fs commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +            sidebarElem.classList.add('open');
for toggle action, it's better if you define a state and use the state for toggling

2022-01-09 07:33 UTC, mehrzad-fs commented on templates/bot.mustache
> +    <span id="sidebar-toggler"></span>
this file is not related to `deriv-bot` project you don't need to update it 
```suggestion
```

2022-01-09 07:33 UTC, mehrzad-fs commented on templates/deriv/index.mustache
> +    <span id="sidebar-toggler"></span>
you can remove it if you move your `<SidebarToggle/>` component inside `<Main/>` component

2022-01-10 08:44 UTC, sandeep-deriv commented on templates/deriv/index.mustache
> +    <span id="sidebar-toggler"></span>
Done

2022-01-10 08:45 UTC, sandeep-deriv commented on templates/bot.mustache
> +    <span id="sidebar-toggler"></span>
Okay, removed

2022-01-10 08:45 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +            sidebarElem.classList.add('open');
Done

2022-01-10 08:45 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +        const togglerElem = document.getElementById('sidebar-toggle-action');
done

2022-01-10 08:45 UTC, sandeep-deriv commented on src/botPage/view/index.js
> +
Moved it inside the SidebarToggle

2022-01-10 08:45 UTC, sandeep-deriv commented on src/botPage/view/View.js
> +    ReactDOM.render(<SidebarToggler />, document.getElementById('sidebar-toggler'));
Sure, Moved it inside `Main` component.
Removed #sidebar-toggler from index.mustache

2022-01-10 08:46 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +        const togglerElem = document.getElementById('sidebar-toggle-action');
done

2022-01-10 08:46 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggler/index.js
> +const SidebarToggler = () => {
done

2022-01-10 08:50 UTC, sandeep-deriv commented on src/botPage/view/index.js
> +            const ele = document.getElementById('sidebar-toggle-action');
Sure, updated names.

2022-01-10 09:11 UTC, salarhfz-fs commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +import cn from 'classnames';
I think it's a convention (so a best practice) to import this library as `classNames`

2022-01-10 09:12 UTC, salarhfz-fs commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +    const toggleRef = React.useRef();
```suggestion
    const toggle_ref = React.useRef();
```

2022-01-10 09:14 UTC, salarhfz-fs commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +    const [open, setOpen] = React.useState(false);
`is_open` to show it's a boolean.
`is_open` => yes/no => boolean!

2022-01-10 09:29 UTC, mehrzad-fs commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +            }
```suggestion
            is_open ? blocklyToolbox.classList.add('open'): blocklyToolbox.classList.remove('open')
```

2022-01-10 09:29 UTC, mehrzad-fs commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +            }
Also, I suggest instead of using `open` class which is too general you can use a better className
e.g:  toolbox__collapse-open toolbox__collapse-close

2022-01-10 09:30 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +import cn from 'classnames';
done

2022-01-10 09:30 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +    const toggleRef = React.useRef();
done

2022-01-10 09:46 UTC, salarhfz-fs approved these changes

2022-01-10 10:14 UTC, sandeep-deriv commented on src/botPage/view/deriv/components/SidebarToggle/index.js
> +            }
done

2022-01-10 12:27 UTC, mehrzad-fs approved these changes

2022-01-12 10:19 UTC, merged